``Bukkit`` performance improvements/cleanup before v5.
LandlordPlugin/LandLord pull request #118
Opened 2022-07-10 08:54 UTC by Aurelien30000

_Partly related to discord's conversation about dynmap extension issues and crash._

- Maintains a Map to fetch more efficiently flags from their id.
- Calls heavy manage event asynchronously _(iirc, former Bukkit like 1.13 forced us to switch back to a full sync management, this is no longer the cas and we don't really care about 1.15-/1.16-)_.
- Seperates lands' icon in lists according to their dimension _(somehow breaking for older versions, configurable items is a TODO, I kept the things simple)_.
- Fix default flag value visibility with non-registered flags in a land. For example, when a custom flag is added to the plugin, lands claimed before this addition do not have the flag registered until a modification is done with the ``/land manage`. However, it's real default value must be shown (~allowed).
- Removes some useless debug comments.

2022-07-14 15:38 UTC, Aurelien30000 commented on LandLord-api/src/main/java/biz/princeps/landlord/api/events/LandManageEvent.java
> +        super(true);
This is not required for it to be fired async. Knowing that this event is currently only used to spread changes, we may let the constructor decide with the given method.

2022-07-17 17:37 UTC, RainbowDashLabs approved these changes

2022-07-29 18:48 UTC, SirYwell requested changes
Finally coming to this...

Changes targeting v4 need to target `master`. We already have v5 changes on `development`.

Calling the event asynchronously is a behavioral change that might cause bugs/exceptions in consuming plugins. As calling the event itself isn't costly, I'm not sure if that's the right approach. Consumers should rather move their work from the main thread instead if needed. For "small" listeners, having the additional threading overhead might be counterproductive.

2022-07-29 19:58 UTC, Aurelien30000 commented
Overall you’re right, but I noticed a big difference for `LandManageEvent`. Other events will be restored to former behavior.

2022-07-30 14:45 UTC, SirYwell commented
> but I noticed a big difference

Can you point out in which cases you found those differences?

2022-07-30 15:07 UTC, Aurelien30000 commented
These changed are based on the following discussion: https://discord.com/channels/432481914608287745/551895083276959754/990543383648952370. For example, `LandManageEvent` is triggered for every modified land during the same tick (manage does not take advantage of multi queue _yet_). When a player owns thousands of lands, server main thread is held calling events, this is more costly than expected. There is the same problem for the consuming plugins that must process these events synchronously. For sure this system is not optimal at all, at the moment, there is no other _easy_ choice for v4 in my opinion. v4 is ended and these changes will be overwritten later with the new event bus.

_As you mentioned, this pr involves a behavioral change. The proposed fix is for a specific usage case. The proof is that it didn't bother before and for years. It doesn't have to absolutely lead to a release, but it can be really useful for some users aware of the inherent risks._

2022-07-30 15:31 UTC, SirYwell approved these changes
Fair enough. I guess we can proceed with this.

2022-07-30 21:33 UTC, merged